/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utilities;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import stream_data.GraphDBManager;
import org.neo4j.driver.v1.Record;
import org.neo4j.driver.v1.Session;
import org.neo4j.driver.v1.StatementResult;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.IOException;

/**
 *
 * @author daniele
 */
public class SubjectChoiceForm extends javax.swing.JFrame {

   Session session;
   static GraphDBManager gdbm;
   String [] topicsArray;
   String topic;
    
    /**
     * Creates new form Form
     */
    public SubjectChoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the SubjectChoiceForm Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        caricaArgomentiButton = new javax.swing.JButton();
        caricaUtentiButton = new javax.swing.JButton();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        checkbox5 = new java.awt.Checkbox();
        manualSearchButton = new javax.swing.JToggleButton();
        confirmButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        picUser1 = new javax.swing.JLabel();
        picUser2 = new javax.swing.JLabel();
        picUser3 = new javax.swing.JLabel();
        picUser4 = new javax.swing.JLabel();
        picUser5 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        screenNameLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        screenNameLabel2 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        screenNameLabel3 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        screenNameLabel4 = new javax.swing.JLabel();
        nameLabel5 = new javax.swing.JLabel();
        screenNameLabel5 = new javax.swing.JLabel();
        manualSearchTextField = new javax.swing.JTextField();
        verifiedLabel1 = new javax.swing.JLabel();
        verifiedLabel2 = new javax.swing.JLabel();
        verifiedLabel3 = new javax.swing.JLabel();
        verifiedLabel4 = new javax.swing.JLabel();
        verifiedLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 150));

        jScrollPane1.setViewportView(jList1);

        caricaArgomentiButton.setText("Carica argomenti");
        caricaArgomentiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaArgomentiButtonActionPerformed(evt);
            }
        });

        caricaUtentiButton.setText("Carica utenti");
        caricaUtentiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaUtentiButtonActionPerformed(evt);
            }
        });

        manualSearchButton.setText("Ricerca utenti manuale");
        manualSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualSearchButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Ottieni i risultati");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Esci");

        picUser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        picUser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        picUser3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        picUser4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        picUser5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameLabel1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        screenNameLabel1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N

        nameLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        screenNameLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N

        nameLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        screenNameLabel3.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N

        nameLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        screenNameLabel4.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N

        nameLabel5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        screenNameLabel5.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N

        manualSearchTextField.setText("Inserisci i nomi utente qui...");
        manualSearchTextField.setToolTipText("Si può inserire anche più di un utente, basta digitare gli screen_name separati da virgola. ATTENZIONE: il sistema è Case Sensitive.");
        manualSearchTextField.setEnabled(false);

        verifiedLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\daniele\\Desktop\\Tesi\\Eseguibili\\config\\rsz_verified.png"));
        verifiedLabel1.setVisible(false);

        verifiedLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\daniele\\Desktop\\Tesi\\Eseguibili\\config\\rsz_verified.png")); // NOI18N
        verifiedLabel2.setVisible(false);

        verifiedLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\daniele\\Desktop\\Tesi\\Eseguibili\\config\\rsz_verified.png")); // NOI18N
        verifiedLabel3.setVisible(false);

        verifiedLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\daniele\\Desktop\\Tesi\\Eseguibili\\config\\rsz_verified.png")); // NOI18N
        verifiedLabel4.setVisible(false);

        verifiedLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\daniele\\Desktop\\Tesi\\Eseguibili\\config\\rsz_verified.png")); // NOI18N
        verifiedLabel5.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkbox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                                .addComponent(checkbox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(picUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verifiedLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(picUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verifiedLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(picUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verifiedLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verifiedLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verifiedLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(screenNameLabel2)
                                    .addComponent(nameLabel2)
                                    .addComponent(screenNameLabel1)
                                    .addComponent(nameLabel1)
                                    .addComponent(screenNameLabel3)
                                    .addComponent(nameLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(caricaArgomentiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(caricaUtentiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manualSearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manualSearchTextField))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(screenNameLabel4)
                                    .addComponent(nameLabel4))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(screenNameLabel5)
                            .addComponent(nameLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(manualSearchButton)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(screenNameLabel1))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(nameLabel1)
                                                .addComponent(manualSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(verifiedLabel1)
                                            .addComponent(picUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(picUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(verifiedLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(screenNameLabel2)))
                                        .addGap(16, 16, 16)))))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(screenNameLabel3))
                                    .addComponent(nameLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caricaArgomentiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(picUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(caricaUtentiButton)
                                    .addComponent(verifiedLabel3))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitButton)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(checkbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(screenNameLabel4))
                                            .addComponent(nameLabel4))
                                        .addGap(60, 60, 60))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(picUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(nameLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(screenNameLabel5)
                                        .addGap(72, 72, 72))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(picUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(verifiedLabel5))
                                        .addGap(61, 61, 61))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(verifiedLabel4)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>                        

    private void caricaArgomentiButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       
    	session = gdbm.getSession();
    	String query = "match (n:Topic) return n.name";
    	StatementResult sr = session.run(query);
    	List<String> topics = new ArrayList<>();
    	while(sr.hasNext()){
    		Record r = sr.next();
    		topics.add(r.get(0).asString());
    	}
    	topicsArray = topics.toArray(new String[0]);
    	
    	jList1.setModel(new javax.swing.AbstractListModel<String>() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			public int getSize() { return topicsArray.length; }
            public String getElementAt(int i) { return topicsArray[i]; }
        });
    	jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);
    }                                                     

    private void caricaUtentiButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        try{
            topic = jList1.getSelectedValue();
        String query = "MATCH (t:Tweet)-[r:MENTIONS]->(u:User), (t)-->(tv:Topic{name:'"+topic+"'})"
                + "\nWHERE exists(u.name)"
                + "\nRETURN u.name, u.screen_name, u.profileImage, u.verified, count(r)"
                + "\nORDER BY COUNT(r) DESC"
                + "\nLIMIT 5 ";
        StatementResult sr = session.run(query);
        int counter = 0;
        while(sr.hasNext()){
            Record r = sr.next();
            if(counter==0){
                nameLabel1.setText(r.get(0).asString());
                screenNameLabel1.setText("@"+r.get(1).asString());
		picUser1.setIcon(new ImageIcon(new URL(r.get(2).asString())));
                if(r.get(3).asBoolean())
                    verifiedLabel1.setVisible(true);

            }
            if(counter==1){
                nameLabel2.setText(r.get(0).asString());
                screenNameLabel2.setText("@"+r.get(1).asString());
		picUser2.setIcon(new ImageIcon(new URL(r.get(2).asString())));
                if(r.get(3).asBoolean())
                    verifiedLabel2.setVisible(true);
            }
            if(counter==2){
                nameLabel3.setText(r.get(0).asString());
                screenNameLabel3.setText("@"+r.get(1).asString());
		picUser3.setIcon(new ImageIcon(new URL(r.get(2).asString())));
                if(r.get(3).asBoolean())
                    verifiedLabel3.setVisible(true);
            }
            if(counter==3){
                nameLabel4.setText(r.get(0).asString());
                screenNameLabel4.setText("@"+r.get(1).asString());
		picUser4.setIcon(new ImageIcon(new URL(r.get(2).asString())));
                if(r.get(3).asBoolean())
                    verifiedLabel4.setVisible(true);
            }
            if(counter==4){
                nameLabel5.setText(r.get(0).asString());
                screenNameLabel5.setText("@"+r.get(1).asString());
		picUser5.setIcon(new ImageIcon(new URL(r.get(2).asString())));
                if(r.get(3).asBoolean())
                    verifiedLabel5.setVisible(true);
            }
            
            counter++;
        }
        } 
        catch(MalformedURLException e){
            e.printStackTrace();
        }
        
    }                                                  

    private void manualSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       if(!manualSearchTextField.isEnabled()){
            manualSearchTextField.setText("");
            manualSearchTextField.setEnabled(true);
            manualSearchTextField.grabFocus();
       }
       else{
           manualSearchTextField.setText("Inserisci i nomi utente qui...");
            manualSearchTextField.setEnabled(false);
            manualSearchButton.grabFocus();
       }
       
    }                                                  

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        List<String> screen_names = new ArrayList<>();
         if(checkbox1.getState())
            screen_names.add(screenNameLabel1.getText().substring(1));
        if(checkbox2.getState())
            screen_names.add(screenNameLabel2.getText().substring(1));
        if(checkbox3.getState())
            screen_names.add(screenNameLabel3.getText().substring(1));
        if(checkbox4.getState())
            screen_names.add(screenNameLabel4.getText().substring(1));
        if(checkbox5.getState())
            screen_names.add(screenNameLabel5.getText().substring(1));
        if(manualSearchTextField.isEnabled()){
            for(String s : manualSearchTextField.getText().split(","))
                screen_names.add(s);
        }
        String params = topic+" ";
        for(String s : screen_names)
            params+=s+" ";
          try {
            Runtime.getRuntime().exec("cmd /c start cmd.exe /K \" cd C:\\Users\\daniele\\Desktop\\Tesi\\Eseguibili && java -jar SubjectHashtags.jar "+params);
        } catch (IOException ex) {
            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectChoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        verifiedLabel1 = new JLabel("");
        verifiedLabel2 = new JLabel("");
        verifiedLabel3 = new JLabel("");
        verifiedLabel4 = new JLabel("");
        verifiedLabel5 = new JLabel("");
        verifiedLabel1.setVisible(false);
        verifiedLabel2.setVisible(false);
        verifiedLabel3.setVisible(false);
        verifiedLabel4.setVisible(false);
        verifiedLabel5.setVisible(false);
        gdbm = new GraphDBManager();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new SubjectChoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton caricaArgomentiButton;
    private javax.swing.JButton caricaUtentiButton;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private java.awt.Checkbox checkbox5;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton manualSearchButton;
    private javax.swing.JTextField manualSearchTextField;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel picUser1;
    private javax.swing.JLabel picUser2;
    private javax.swing.JLabel picUser3;
    private javax.swing.JLabel picUser4;
    private javax.swing.JLabel picUser5;
    private javax.swing.JLabel screenNameLabel1;
    private javax.swing.JLabel screenNameLabel2;
    private javax.swing.JLabel screenNameLabel3;
    private javax.swing.JLabel screenNameLabel4;
    private javax.swing.JLabel screenNameLabel5;
    private static javax.swing.JLabel verifiedLabel1;
    private static javax.swing.JLabel verifiedLabel2;
    private static javax.swing.JLabel verifiedLabel3;
    private static javax.swing.JLabel verifiedLabel4;
    private static javax.swing.JLabel verifiedLabel5;
    // End of variables declaration                   
}
